config/urls.py
from django.contrib import admin
from django.urls import path, include

from config.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portal.urls'), name='portal'),
    path('accounts/', include('allauth.urls')),
]

if DEBUG:
    urlpatterns += [path("__debug__/", include('debug_toolbar.urls')),
    ]

portal/urls.py
from django.urls import path
from .views import NewsList, NewsDetail, PublicationCreate, PublicationUpdate, PublicationDelete, subscriptions

app_name = 'portal'

urlpatterns = [
   path('list/', NewsList.as_view(), name='list_news'),
   path('detail/<int:pk>', NewsDetail.as_view(), name='detail_news'),
   path('news/create/', PublicationCreate.as_view(), name='publication_create'),
   path('news/<int:pk>/edit/', PublicationUpdate.as_view(), name='publication_update'),
   path('news/<int:pk>/delete/', PublicationDelete.as_view(), name='publication_delete'),
   path('article/create/', PublicationCreate.as_view(), name='publication_create'),
   path('article/<int:pk>/edit/', PublicationUpdate.as_view(), name='publication_update'),
   path('article/<int:pk>/delete/', PublicationDelete.as_view(), name='publication_delete'),
   path('subscriptions/', subscriptions, name='subscriptions'),
]

portal/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    author_user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="author"
    )
    rating = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"

    def __str__(self):
        return f'{self.author_user.username}'

    def update_rating(self):
        post_rating = self.post_set.aggregate(p_rating=Sum("rating")).get("p_rating")
        if post_rating is None:
            post_rating = 0
        comm_rating = self.author_user.comment_set.aggregate(
            c_rating=Sum("rating")
        ).get("c_rating")
        if comm_rating is None:
            comm_rating = 0
        post_comm_rating = (
            Comment.objects.filter(user_comment__author=self)
            .aggregate(pc_rating=Sum("rating"))
            .get("pc_rating")
        )
        if post_comm_rating is None:
            post_comm_rating = 0
        self.rating = post_rating * 3 + comm_rating + post_comm_rating
        self.save()


class Category(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f"Категория: {self.name}"

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    CHOICE = [
        ("NW", "Новость"),
        ("AR", "Статья"),
    ]
    field_choice = models.CharField(max_length=2, choices=CHOICE, default="NW")
    time_in = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through="PostCategory")
    header = models.CharField(max_length=150)
    content = models.TextField()
    rating = models.IntegerField(default=0)

    def get_absolute_url(self):
        return reverse('portal:detail_news', args=[str(self.id)])

    class Meta:
        verbose_name = "Публикация"
        verbose_name_plural = "Публикации"

    def like(self):
        self.rating = self.rating + 1
        self.save()

    def dislike(self):
        self.rating = self.rating - 1
        self.save()

    def preview(self):
        return self.content[:123] + "..."

    def __str__(self):
        return f"{self.author}"

    def __repr__(self):
        return self.__str__()


class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    time_comment = models.DateTimeField(auto_now_add=True)
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating = self.rating + 1
        self.save()

    def dislike(self):
        self.rating = self.rating - 1
        self.save()


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Subscription(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name='subscriptions')
    category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='subscriptions')

portal/forms.py
from IPython.core.release import author
from django import forms
from django.core.exceptions import ValidationError

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["author", "header", "content", "category"]

portal/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Exists, OuterRef
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_protect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from .filters import NewsFilter
from .forms import PostForm
from .models import Post, Category, Subscription
from .tasks import send_emails, send_emails_weekly


class NewsList(ListView):
    model = Post
    ordering = '-time_in'
    template_name = 'news.html'
    context_object_name = 'news_list'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = NewsFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filterset"] = self.filterset
        return context


class NewsDetail(DetailView):
    model = Post
    template_name = 'news_detail.html'
    context_object_name = 'news_detail'


class PublicationCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('portal.add_post',)
    form_class = PostForm
    model = Post
    template_name = "publication_edit.html"

    def form_valid(self, form):
        _var = form.save(commit=False)
        if self.request.path.split('/')[1] == 'article':
            _var.field_choice = "AR"
        _var.save()
        send_emails.delay(_var.id)
        return super().form_valid(form)


class PublicationUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('portal.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'publication_edit.html'

    def form_valid(self, form):
        _var = form.save(commit=False)
        if self.request.path.split('/')[1] == 'news':
            _var.field_choice = "NW"
        elif self.request.path.split('/')[1] == 'article':
            _var.field_choice = "AR"
        return super().form_valid(form)


class PublicationDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('portal.delete_post',)
    model = Post
    template_name = 'publication_delete.html'
    success_url = reverse_lazy('portal:list_news')


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':
        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscription.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscription.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscription.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'category.html',
        {'categories': categories_with_subscriptions},
    )

portal/templates/category.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

portal/templates/news.html
{% extends 'flatpages/default.html' %}
{% load my_filters %}

{% block title %}Список новостей{% endblock title %}

{% block navbar %} NewsPortal {% endblock navbar %}

{% block content %}
    <h2>Количество новостей: {{ news_list|length }}</h2>

    <form method="get">
        {{ filterset.form.as_p }}
        <button type="submit">Фильтровать</button>
    </form>
    <h2>{{ news_detail }}</h2>
    <hr>
    {% if perms.portal.add_post %}
        <a href="{% url 'portal:publication_create' %}">Добавить публикацию</a>
    {% endif %}
    <table>
        <tr>
            <td>Заголовок</td>
            <td>Дата публикации</td>
            <td>Превью</td>
        </tr>
        {% for news in news_list %}
            <tr>
                <td>{{ news.header }}</td>
                <td>{{ news.time_in | date:'M d Y' }}</td>
                <td> {{ news.content | truncatechars:100 }}</td>
            </tr>
            
                <td>
                    {% if perms.portal.change_post %}
                    <a href="{% url 'portal:publication_update' pk=news.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.portal.delete_post %}
                    <a href="{% url 'portal:publication_delete' news.id %}">Удалить</a>
                    {% endif %}
                </td>
            
        {% endfor %}
    </table>

    {% if page_obj.has_previous %}
        <a href="?page=1">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}
{% endblock content %}

portal/templates/news_detail.html
{% extends 'flatpages/default.html' %}
{% load my_filters %}

{% block title %}Детальная информация{% endblock title %}

{% block content %}
<h2>Описание публикации</h2>
<hr>
    <table>
        <tr>
            <td>Заголовок</td>
            <td>Дата публикации</td>
            <td>Превью</td>
            <td>Автор</td>
            <td>Рейтинг</td>
        </tr>
        <tr>
            <td>{{ news_detail.header | correct_words}}</td>
            <td>{{ news_detail.content | correct_words}}</td>
            <td>{{ news_detail.time_in |date:'M d Y' }}</td>
            <td>{{ news_detail.author.author_user }}</td>
            <td>{{ news_detail.rating }}</td>
        </tr>
    </table>
{% endblock content %}

portal/templates/publication_delete.html
{% extends 'flatpages/default.html' %}

{% block navbar %}E-Shop{% endblock navbar %}

{% block content %}
<h1>Удаление публикации</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.header }}"?</p>
    <p>{{ object.author }}</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

portal/templates/publication_edit.html
{% extends 'flatpages/default.html' %}

{% block navbar %}E-Shop{% endblock navbar %}

{% block content %}
<h1>Публикация</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %} 

portal/templates/weekly_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h3> Свежие публикации за неделю </h3>
<ul>
    {% for post in posts %}
        <li> <a href="{{ link }}{% url 'portal:detail_news' post.pk %}">{{ post.header }}</a></li>
    {% endfor %}
</ul>
</body>
</html>